<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0-ios</TargetFramework>
        <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.iOS"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MeowPlayer\MeowPlayer.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <NativeReference Include="..\External\libs\un4seen_bass\ios\bass.xcframework" Kind="Framework" SmartLink="False" ForceLoad="True"/>
    </ItemGroup>
</Project>
