name: MeowPlayer - mobile build

on:
  push:
  pull_request:

jobs:
  build:
    name: MeowPlayer Mobile (${{ matrix.targets }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          include:
          # Android
          - os: ubuntu-latest
            targets: "android-x86"
            platform: Android

          - os: ubuntu-latest
            targets: "android-x64"
            platform: Android

          - os: ubuntu-latest
            targets: "android-arm"
            platform: Android

          - os: ubuntu-latest
            targets: "android-arm64"
            platform: Android


          # iOS
          - os: macos-latest
            targets: "ios-arm64"
            platform: iOS


    steps:
      - name: Pull repo
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name:  Setup dotnet
        uses: actions/setup-dotnet@v6
        with:
            dotnet-version: '10.0.101'

      - name: Build MeowPlayer
        if: matrix.platform == 'Android'
        shell: bash
        run: |
            dotnet workload restore MeowPlayer.Android/MeowPlayer.Android.csproj
            for target in ${{ matrix.targets }}; do
              dotnet publish MeowPlayer.Android/MeowPlayer.Android.csproj -c Release -r $target
            done

      - name: Build MeowPlayer
        if: matrix.platform == 'iOS'
        shell: bash
        run: |
            dotnet workload restore MeowPlayer.iOS/MeowPlayer.iOS.csproj
            for target in ${{ matrix.targets }}; do
              dotnet publish MeowPlayer.iOS/MeowPlayer.iOS.csproj -c Release -r $target /p:BuildIpa=true /p:EnableCodeSigning=false /p:CodesignRequireProvisioningProfile=false /p:SuppressTrimAnalysisWarnings=true
            done

      - name: Dir ls
        shell: bash
        run: |
            ls -al build
            pwd

